#include "ofxGamepadConfigs.h"

//KNOWN_CONTROLLER_NAMES = malloc(sizeof(char*)*5);
//KNOWN_CONTROLLER_NAMES[0] = PS3_NAME;
//KNOWN_CONTROLLER_NAMES[1] = XBOX_NAME;
//KNOWN_CONTROLLER_NAMES[2] = XBOX_WIRELESS_NAME;
//KNOWN_CONTROLLER_NAMES[3] = OUYA_NAME;
//KNOWN_CONTROLLER_NAMES[4] = NULL;

char *KNOWN_CONTROLLER_NAMES[5] = {
    PS3_NAME,
    XBOX_NAME,
    XBOX_WIRELESS_NAME,
    OUYA_NAME,
    0
};
